DataBaseControl/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.urls import include
from . import views

app_name = "DataBase"

urlpatterns = [
   path('DataStore/',views.DataControl,name="data"),
   path('ShoseData/',views.Shose_Data_Load,name="Shose"),
   path('ShoseView/<str:Shosename>',views.Shose_Data_View,name="ShoseData"),
   path('ShoseAdd/',views.Shose_add_New,name="ShoseAdd"),
   path('ShoseChange/<str:Shosename>',views.Shose_Change_Data,name="ShoseChange"),
   path('ShoseChange/<str:Shosename>/Done',views.Shose_Data_Change,name="ShoseDataChange"),
   path('ShoseDel/<str:Shosename>',views.Shose_del,name="ShoseDelete"),
   path('ShoseComment/<str:Shosename>',views.Shose_Comment_List,name="CommentList"),
   path('ShoseComment/<str:Shosename>/Add',views.Shose_Comment_Add,name="AddComment"),
   path('ShoseComment/<str:Shosename>/<str:path>',views.Shose_Comment_Views,name="ShoseCommentView"),
   path('ShoseComment/<str:Shosename>/<str:path>/Change',views.Shose_Comment_Rewrite,name="ChangeComment"),
   path('ShoseComment/<str:Shosename>/<str:path>/Delete',views.Shose_Comment_Del,name="CommentDelete"),
   path('Logs/', views.Logs_List,name="Logs"),
   path('Logs/<str:path>/Del',views.Logs_Del,name="LogsDelete"),
   path('Logs/<str:path>',views.Logs_View,name="LogsView"),
   path('Users/',views.User_List,name="Users"),
   path('Users/<str:uid>',views.User_View,name="UsersView"),
   path('Users/<str:uid>/Change',views.User_Change,name="UsersChange"),
   path('Users/<str:uid>/Delete',views.User_Del,name="UsersDelete"),
   path('Users/<str:uid>/logs',views.User_Logs,name="UsersLog"),
   path('Users/<str:uid>/<str:path>',views.User_Logs_View,name="UsersLogView"),
   path('Users/<str:uid>/<str:path>/Delete',views.User_Logs_Del,name="UsersLogDel"),
   path('apijson/',views.User_Log_Json,name="UserLogsJson"),
   


   


]

SignAccount/urls.py
from django.urls import path
from django.urls import re_path
import sys

from . import views

app_name = "SAccount"

urlpatterns = [
    path('login/',views.signin,name="signin"),
    path('logout/',views.logout,name="logout"),
    path('SignUp/',views.SignUp,name="SignUp"),    
    path('deleted/',views.deleteuser,name="del"),
    path('cancel/',views.deleteCancel,name="cancel"),
]

serverDatabase/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.urls import include
from . import views
#from testapp import views

app_name = "MainHome"

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$',views.homePage,name="Home"),
    re_path(r'^Server/Account',include('SignAccount.urls')),
    re_path(r'^Server/DataBase',include('DataBaseControl.urls')),
]

templates/AddData.html
{%load static%}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta http-equiv = "X-UA-Compatible" content = "IE = edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ex.css' %}">
    <title>{%block title%}{%endblock%}</title>
</head>
<body>
    
    {%block content%}
    {%endblock%}

</body>

</html>

templates/DataBase.html
<!DOCTYPE html>
{% extends 'DataBaseView.html'%}
{%block title%}어서오세요{%endblock%}
{%block content%}
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h1>데이터베이스 목록</h1>
                    <h2>데이터베이스 목록</h2>
                </div>
                <div class="list-group">
                    <a href="{%url "DataBase:Users" %}" class="list-group-item">유저</a>
                    <a href="{%url "DataBase:Shose"%}" class="list-group-item">신발</a>
                    <a href="{%url "DataBase:Logs" %}" class="list-group-item">로그</a>
                </div>
            </div>
        </div>
        <div class="row">
            <a class="btn btn-primary" href="{% url 'Home' %}">돌아가기</a>

        </div>
    </div>
    
    
{%endblock%}

templates/LogsList.html
{%extends 'DataBaseView.html'%}
{%block title%}로그{%endblock%}
{%block content%}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h1> 로그정보 </h1>
                </div>
                <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">#</th>
                        <th scope="col">날짜</th>
                        <th scope="col">이름</th>
                        <th scope="col">uid</th>
                        <th scope="col">신발</th>
                    </tr>
                </thead>
                <tbody>
                    {%for LogsList in Logs %}
                        <tr onclick="location.href='{% url 'DataBase:LogsView' LogsList.path %}'">
                            <th scope="row"> {{ forloop.counter }}</th>
                            <td> {{ LogsList.timeStamp }} </td>
                            <td> {{ LogsList.user }} </td>
                            <td> {{ LogsList.uid}} </td>
                            <td> {{ LogsList.shoses}} </td>
                        </tr>
                    {%endfor%}
                </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="btn-group" role="group" aria-label="button list">

                <a class="btn btn-primary" href="{% url "DataBase:data" %}" aria-label="list">돌아가기</a>

        </div>
    </div>
{%endblock%}

templates/LogsView.html
<!DOCTYPE html>
{% extends 'DataBaseView.html' %}
{% block title%}로그조회{%endblock%}
{% block content%}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered border-primary table-hover table-striped">
                    <tr>
                        <th scope="col">uid</th>
                        <td>{{Logs.uid}}</td>
                    <tr>
                    <tr>
                        <th scope="col">이름</th>
                        <td>{{Logs.user}}</td>
                    <tr>
                    <tr>
                        <th scope="col">신발 이름</th>
                        <td>{{Logs.shoses}}</td>
                    </tr>
                    <tr>
                        <th scope="col">시간</th>
                        <td>{{Logs.timeStamp}}</td>
                    </tr>
                    <tr>
                        <th scope="col">종류</th>
                        <td>{{Logs.category}}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="btn-group" role="group">
                <a href="{% url "DataBase:Logs" %}" class="btn btn-primary" aria-lebel="List">목록</a>
                <a href="{% url "DataBase:LogsDelete" path %}" class="btn btn-danger" aria-lebel="delete">삭제</a>
            </div>
        </div>
    </div>
{%endblock%}

templates/ShoseCommentAdd.html
{% extends 'AddData.html'%}
{% block title %}
{{Shosename}} 후기 추가
{%endblock%}
{%block content%}
<div class="container-fluid">
    <form action="{%url 'DataBase:AddComment' Shosename %}" method="POST" class="my-3">
    {% csrf_token %}
        <div class="row">
            <label for="Username" class="col-md-1 col-form-label" >유저명</label>
            <div class="col-md-11">
                <input type="text" readonly class="form-control-plaintext" id="Username" name="name" value="{{username}}">
            </div>
        </div>
        <div class="row">
            <div class="col-md mb-3">
                <div class="form-floating">
                    <textarea class="form-control" id="CommentArea" name="comment" style="height: 100px" placeholder="후기"></textarea>
                    <label for="CommentArea" class="form-label" name="comment">후기</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md mb-3">
                <input type="hidden" name="uid" value={{uid}}>
            </div>
        </div>
        <div class="row">
            <div class="col-md mb-3">
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="등록">
                </div>
            </div>
        </div>
    </form>
</div>




{%endblock%}

templates/ShoseCommentDel.html
{% extends 'DelData.html'%}
{%block title%}신발 {{name}}의 후기 삭제{%endblock%}
{% if messages %}
    {%for message in messages%}
        {{message.tags}}
        {{message.message}}
    {% endfor %}
{% endif %}
{%block content%}
<div class="container-fluid">
    <form action="{% url 'DataBase:CommentDelete' name path %}" method="POST" class"my-3">
    {% csrf_token %}
        <div class="row">
            <div class="col-md mb-3">
                <div class="alert alert-danger">정말로 해당 후기를 삭제하시겠습니까?</div>
                <a href="{% url 'DataBase:ShoseCommentView' name path %}" class="btn btn-primary">취소</a>
                <input type="submit" value="삭제" class="btn btn-danger">
            </div>
        </div>
    </form>

</div>
{%endblock%}

templates/ShoseCommentView.html
<!DOCTYPE html>
{% extends 'DataBaseView.html' %}
{% block title%}{{name}}의 후기중 {{comment.name}}의 후기, {{comment.timestamp}} {%endblock%}
{% block content%}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered border-primary table-hover table-striped">
                    <tr>
                        <th scope="col">이름</th>
                        <td>{{comment.name}}</td>
                    <tr>
                    <tr>
                        <th scope="col">시간</th>
                        <td>{{comment.timestamp}}작성{% if comment.rewrite %}{{comment.rewrite_timestamp}}수정{% endif %}</td>
                    </tr>
                    <tr>
                        <th scope="col">후기</th>
                        <td>{{comment.comment}}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="btn-group" role="group">
                <a href="{% url "DataBase:CommentList" name %}" class="btn btn-primary" aria-lebel="List">목록</a>
                <a href="{% url "DataBase:ChangeComment" name path %}" class="btn btn-primary">수정</a>
                <a href="{% url "DataBase:CommentDelete" name path %}" class="btn btn-danger" aria-lebel="delete">삭제</a>
                
            </div>
        </div>
    </div>
{%endblock%}

templates/ShoseData.html
{%extends 'DataBaseView.html'%}
{%block title%}신발{%endblock%}
{%block content%}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h1> 신발정보 </h1>
                </div>
                <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">#</th>
                        <th scope="col">이름</th>
                    </tr>
                </thead>
                <tbody>
                    {%for ShoseData in Shose%}
                        <tr onclick="location.href='{% url 'DataBase:ShoseData' ShoseData.name %}'">
                            <th scope="row"> {{ forloop.counter }}</th>
                            <td> {{ ShoseData.name }} </td>
                        </tr>
                    {%endfor%}
                </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="btn-group" role="group" aria-label="button list">

                <a class="btn btn-primary" href="{% url "DataBase:data" %}" aria-label="list">돌아가기</a>
                <a class="btn btn-primary" href="{% url "DataBase:ShoseAdd" %}" aria-label="ShoseAdd">추가</a>

        </div>
    </div>
{%endblock%}

templates/ShoseDataView.html
<!DOCTYPE html>
{% extends 'DataBaseView.html' %}
{% block title%}{{Shose.name}}{%endblock%}
{% block content%}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered border-primary table-hover table-striped">
                    <tr>
                        <th scope="col">이름</th>
                        <td>{{Shose.name}}</td>
                    <tr>
                    <tr>
                        <th scope="col">브랜드</th>
                        <td>{{Shose.brand}}</td>
                    </tr>
                    <tr>
                        <th scope="col">가격</th>
                        <td>{{Shose.price}}</td>
                    </tr>
                    <tr>
                        <th scope="col">색상</th>
                        <td>{% for color in Shose.color%}{{color}} {%endfor%}</td>
                    </tr>
                    <tr>
                        <th scope="col">이미지</th>
                        <td><img src="{{Shose.image}}" width="50%" height="50%"></td>
                    </tr>
                    <tr>
                        <th scope="col">평점</th>
                        <td>{% if Shose.rate != None %}{{Shose.rate}}{% else %}0.0{% endif %}</td>
                    </tr>
                    <tr>
                        <th scope="col">후기</th>
                        <td><a class="btn btn-primary" href="{% url "DataBase:CommentList" Shose.name %}">목록</a></td>
                    </tr>


                </table>
            </div>
        </div>
        <div class="row">
            <div class="btn-group" role="group" aria-lebel="ShoseData">
                <a href="{% url "DataBase:Shose"%}" class="btn btn-primary" aria-lebel="List">목록</a>
                <a href="{% url "DataBase:ShoseChange" Shose.name%}" class="btn btn-primary" aria-lebel="Change">수정</a>
                <a href="{% url "DataBase:ShoseDelete" Shose.name %}" class="btn btn-danger" aria-lebel="delete">삭제</a>
                
            </div>
        </div>
    </div>
{%endblock%}

templates/SignUp.html
{% if message %}
<script>
    alert('{{message}}');
</script>
{% endif %}
{%load static%}
<!DOCTYPE html>
<html lang='ko'>
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ex.css' %}">
    <title>SignUp</title>
</head>
<body>
    <div class="container-fluid">
        <form action="{% url 'SAccount:SignUp' %}" method="POST" class="my-3">
        {% csrf_token %}
            <div class="row">
                <div class="col-xs-6 col-md-3">
                    <div class="form-floating">
                        <input type="text" class="form-control" placeholder="홍길동" name="name" id="Username">
                        <label for="Username">이름</label>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="form-floating">
                        <input type="number" class="form-control" id="Userage" placeholder="25" name="age">
                        <label for="Userage">나이</label>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="form-floating">
                        <input type="email" class="form-contorl" id="Useremail" placeholder="example@example.com" name="email">
                        <label for="Useremail">이메일</label>
                    </div>
                </div>
                <div class = "col-xs-6 col-md-3">
                    <div class="form-floating">
                        <select class="form-select" id="UserGender" name="gender">
                            <option selected value="">아무성별<option>
                            <option value="male">남자</option>
                            <option value="female">여자</option>
                            <option value="other">기타</option>
                        </select>
                        <label for="UserGender">성별</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-floating">
                    <input type="password" class="form-control" id="Userpassword" placeholder="PassW0rd" name="password">
                    <label for="Userpassword">비밀번호</label>
                </div>
            </div>

            <input type="submit" class="btn btn-primary" value="회원가입">
        </form>
    </div>
</body>
</html>

templates/UserList.html
{%extends 'DataBaseView.html'%}
{%block title%}유저{%endblock%}
{%block content%}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h1> 유저정보 </h1>
                </div>
                <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">#</th>
                        <th scope="col">uid</th>
                        <th scope="col">이름</th>
                    </tr>
                </thead>
                <tbody>
                    {%for User in UserList %}
                        <tr onclick="location.href='{% url 'DataBase:UsersView' User.uid %}'">
                            <th scope="row"> {{ forloop.counter }}</th>
                            <td> {{ User.uid }} </td>
                            <td> {{ User.name }} </td>
                        </tr>
                    {%endfor%}
                </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="btn-group" role="group" aria-label="button list">

                <a class="btn btn-primary" href="{% url "DataBase:data" %}" aria-label="list">돌아가기</a>

        </div>
    </div>
{%endblock%}

templates/UserViews.html
<!DOCTYPE html>
{% extends 'DataBaseView.html' %}
{% block title%}{{User.name}}조회{%endblock%}
{% block content%}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered border-primary table-hover table-striped">
                    <tr>
                        <th scope="col">uid</th>
                        <td>{{User.uid}}</td>
                    <tr>
                    <tr>
                        <th scope="col">이름</th>
                        <td>{{User.name}}</td>
                    </tr>
                    <tr>
                        <th scope="col">email</th>
                        <td>{{User.email}}</td>
                    </tr>
                    <tr>
                        <th scope="col">나이</th>
                        <td>{{User.age}}</td>
                    </tr>
                    <tr>
                        <th scope="col">성별</th>
                        <td>{{User.Gender}}</td>
                    </tr>
                    <tr>
                        <th scope="col">admin</th>
                        <td>{{User.admin}}</td>
                    </tr>
                    <tr>
                        <th scope="col">기록</th>
                        <td><a href="{% url "DataBase:UsersLog" User.uid %}" class="btn btb-primary">목록</a>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="btn-group" role="group">
                <a href="{% url "DataBase:Users" %}" class="btn btn-primary" aria-lebel="List">목록</a>
                <a href="{% url "DataBase:UsersChange" User.uid %}" class="btn btn-primary" aria-lebel="Change">수정</a>
                <a href="{% url "DataBase:UsersDelete" User.uid %}" class="btn btn-danger" aria-lebel="delete">삭제</a>
            </div>
        </div>
    </div>
{%endblock%}

templates/UsersLogsDel.html
{% extends 'DelData.html'%}
{%block title%}로그 삭제{%endblock%}
{% if messages %}
    {%for message in messages%}
        {{message.tags}}
        {{message.message}}
    {% endfor %}
{% endif %}
{%block content%}
<div class="container-fluid">
    <form action="{% url 'DataBase:UsersLogsDel' uid path %}" method="POST" class"my-3">
    {% csrf_token %}
        <div class="row">
            <div class="col-md mb-3">
                <div class="alert alert-danger">정말로 해당 로그를 삭제하시겠습니까?</div>
                <a href="{% url 'DataBase:UsersLogView' uid path %}" class="btn btn-primary">취소</a>
                <input type="submit" value="삭제" class="btn btn-danger">
            </div>
        </div>
    </form>

</div>
{%endblock%}

templates/Welcome.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ex.css' %}">
    <title>어서오세요</title>
</head>
<body>
{% csrf_token %}

    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="btn-group form-control">
                    <button type="button" onclick="location.href='{% url 'SAccount:logout' %}'" class="btn btn-primary">로그아웃</button>
                    <button type="button" onclick="location.href='{% url 'SAccount:del' %}'" class="btn btn-primary">회원탈퇴</button>
                    <button type="button" onclick="location.href='{% url 'DataBase:data' %}'" class="btn btn-primary">데이터베이스</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                어서오세요 {{e}}님
            </div>
        </div>
    </div>

</body>
</html>